routes/web.php
<?php

use App\Region;
use App\Comuna;


Route::group(['middleware' => ['web']], function () {
    
    Route::get('/login', function () {
        return view('auth/login');
    })->name('login');

	Route::post('/login', 'Auth\LoginController@login');
});


Route::group(['middleware' => ['auth', 'web']], function () {
	Route::post('logout', 'Auth\LoginController@logout')->name('logout');

	Route::get('/', function () {
	    return view('welcome');
	})->name('index');

	Route::get('find', 'SearchController@find');
	
	Route::get('paciente/search', 'PacienteController@autocomplete')->name('paciente.search');
	Route::resource('paciente', 'PacienteController');
	Route::resource('medico', 'MedicoController');
	Route::resource('usuario', 'UserController');
	Route::resource('roles', 'RolesController');
	Route::resource('agenda', 'AgendaController');
	Route::resource('sucursal', 'SucursalController');
	Route::resource('informe', 'InformeMedicoController');
	Route::resource('nefrologia', 'NefrologiaController');
	Route::resource('evolucion', 'EvolucionController');
	Route::resource('historial', 'HistorialController');
	Route::resource('horario', 'MedicoHorarioController');

	Route::get('historial/{id}/paciente/evolucion/mostrar', 'HistorialController@mostrarEvolucion')->name('mostrarEvolucion');

	Route::get('impresion/{id}/informe/medico', 'ImpresionesController@infMedico')->name('impresion.infMedico');
	Route::get('impresion/{id}/informe/nefrologia', 'ImpresionesController@infNefrologico')->name('impresion.infNefrologico');
	Route::get('impresion/{id}/informe/evolucion', 'ImpresionesController@infEvolucion')->name('impresion.infEvolucion');

	Route::post('configuracion/usuario/sucursal', 'UserConfiguracionController@cambioSucursal')->name('usuario.configuracion.sucursal');

	Route::get('paciente/{id}/comprobar', function($rut) {
	    $paciente = \App\Paciente::where('rut', str_replace('.', '', $rut))->where('rut_v', digitoVerificador($rut))->first();
	    if (count($paciente)>0) {
	    	return response()->json(['paciente' => $paciente, 'result' => true]);
	    }
	    return response()->json(['paciente' => [], 'result' => false]);
	})->name('paciente.comprobar');

	Route::get('global/regiones/{pais_id}', function ($pais_id) {
		return Region::where('pais_id', $pais_id)->orderBy('descripcion')->pluck('descripcion', 'id');
	})->name('global.regiones');

	Route::get('global/comunas/{region_id}', function ($region_id) {
		return Comuna::where('region_id', $region_id)->orderBy('descripcion')->pluck('descripcion', 'id');
	})->name('global.comunas');

	Route::get('digito/verificador/{rut}', function($rut){
		$digito = digitoVerificador($rut);
		return response()->json($digito);
	})->name('digito.verificador');

});

app/Paciente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Paciente extends Model
{
    protected $table = 'pacientes';

    protected $guarded = [];


    public function contacto()
    {
        return $this->hasOne('App\PacienteContacto');
    }

    public function diagnostico()
    {
        return $this->hasOne('App\PacienteDiagnostico');
    }

    //HISTORIAL MEDICO DEL PACIENTE

    public function infMedico()
    {
        return $this->hasMany('App\InfMedico');
    }

    public function infNefrologico()
    {
        return $this->hasMany('App\InfNefrologia');
    }

    public function infEvoMedica()
    {
        return $this->hasMany('App\InfEvoMedica');
    }
}

app/Http/Controllers/PacienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\PacienteRequest;
use App\DataTables\PacientesDataTable;

use App\Pais;
use App\Region;
use App\Ciudad;
use App\Paciente;
use App\PacienteContacto;
use App\PacienteDiagnostico;

use DB;

class PacienteController extends Controller
{
    public function index(PacientesDataTable $dataTable)
    {
        return $dataTable->render('paciente.index');

    	return view('paciente.index', [
            'pacientes' => Paciente::paginate(12),
            ]);
    }

    public function create()
    {
    	return view('paciente.create', [
            'paises' => Pais::orderBy('descripcion')->pluck('descripcion', 'id'),
            ]);
    }

    public function store(PacienteRequest $request)
    {
        
        $paciente = Paciente::firstOrCreate([
                    'rut'                   => str_replace('.', '', $request->rut),
                    'rut_v'                 => digitoVerificador($request->rut),
                    'nombres'               => $request->nombres,
                    'apellidos'             => $request->apellidos,
                    'pais_nacimiento_id'    => $request->pais_nacimiento_id,
                    'pais_nacionalidad_id'  => $request->pais_nacionalidad_id,
                    'sexo'                  => $request->sexo,
                ]);
        
        $contacto  = new PacienteContacto($request->only(['telefono', 'celular', 'email', 'direccion']));
        $paciente->contacto()->save($contacto);
        
        //$diagnostico    = new PacienteDiagnostico($request->only(['sintomas', 'diagnostico']));
        //$paciente->diagnostico()->save($diagnostico);

        alert()->success('se registró la información del paciente '. $paciente->nombres.', '.$paciente->apellidos, '¡Completado!')->persistent('Aceptar');
        return redirect()->route('paciente.index');
    }

    public function show($id)
    {
        $paciente = DB::select('CALL paciente_info('.$id.')');
        $paciente = collect($paciente)->first();
        return response()->json($paciente);
        
        $paciente = Paciente::find($id);
        $paciente = collect($paciente)->merge($paciente->contacto);
    }

    public function edit($id)
    {
        $paciente = Paciente::find($id);
        $paises = Pais::orderBy('descripcion')->pluck('descripcion', 'id');

        /*
        $pacienteInfo = collect($paciente)->toArray();
        $pacienteInfo = (collect($paciente->contacto)->isEmpty()) ? $pacienteInfo : $pacienteInfo+collect($paciente->contacto)->toArray();
        */

        return view('paciente.edit', ['paciente' => $paciente, 'paises' => $paises]);
    }

    public function update(Request $request, $id)
    {
        #dd($request->all());

        $paciente = Paciente::find($id);
        $paciente->fill([
                'rut'                   => str_replace('.', '', $request->rut),
                'rut_v'                 => digitoVerificador($request->rut),
                'nombres'               => $request->nombres,
                'apellidos'             => $request->apellidos,
                'sexo'                  => $request->sexo,
                'edo_civil'             => $request->edo_civil,
                'pais_nacimiento_id'    => $request->pais_nacimiento_id,
                'pais_nacionalidad_id'  => $request->pais_nacionalidad_id
            ]);

        $paciente->contacto->fill([
                'telefono' => $request->telefono,
                'celular' => $request->celular,
                'email' => $request->email,
                'direccion' => $request->direccion,
            ]);

        alert()->basic('Los datos del paciente <strong>'.$paciente->nombres.' '.$paciente->apellidos.'</strong> han sido actualizados satisfactoriamente.', 'Actualizado')->html()->persistent('Aceptar');
        return redirect()->route('paciente.index');
    }

    public function autocomplete(Request $request)
    {

        return Paciente::search($request->get('q'))->get();

        $data = Paciente::select("nombres")
                        ->where('nombres', 'LIKE', "%{$request->input('query')}%")
                        ->get();
        return response()->json($data);
    }
}

resources/views/paciente/create.blade.php
@extends('layouts.app')

@push('js-files')
{!! Html::script('assets/js/plugins/forms/wizards/stepy.min.js') !!}
{!! Html::script('assets/js/plugins/forms/styling/uniform.min.js') !!}
{!! Html::script('assets/js/plugins/forms/selects/select2.min.js') !!}

{!! Html::script('assets/js/plugins/notifications/pnotify.min.js') !!}
{!! Html::script('assets/js/plugins/forms/inputs/formatter.min.js') !!}


@endpush

@push('js')
{!! Html::script('vendor/jsvalidation/js/jsvalidation.js') !!}
{!! JsValidator::formRequest('App\Http\Requests\PacienteRequest', '#frmCreatePaciente'); !!}

{!! Html::script('js/paciente-create.js') !!}
@endpush

@section('page-title', 'Registro de paciente')

@section('content')
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
{!! Form::open(['route' => 'paciente.store', 'autocomplete' => 'off', 'id' => 'frmCreatePaciente']) !!}
<div class="row">
	<div class="col-md-8 col-lg-offset-2">
		<div class="panel panel-flat border-top-lg border-top-primary">
			<div class="panel-heading">
				<h5 class="panel-title">Datos personales</h5>
			</div>
			<div class="panel-body">

				<div class="col-md-4">

					<div class="form-group  form-group-xs">
						{!! Form::label('rut', 'RUT', ['class' => '']) !!}
						<div class="input-group">
							{!! Form::text('rut', null, ['class' => 'form-control text-bold rut']) !!}
							<span class="input-group-addon">-&nbsp;&nbsp; </span>
						</div>

					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group form-group-xs">
						{!! Form::label('nombres', '', ['class' => '']) !!}
						{!! Form::text('nombres', null, ['class' => 'form-control input-roundless text-bold']) !!}
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group form-group-xs">
						{!! Form::label('apellidos', 'Apellidos', ['class' => '']) !!}
						{!! Form::text('apellidos', null, ['class' => 'form-control input-roundless text-bold']) !!}
					</div>
				</div>
				
				<div class="clearfix"></div>
				
				<div class="col-md-4">
					<div class="form-group form-group-xs">
						{!! Form::label('sexo', '', ['class' => '']) !!}
						{!! Form::select('sexo', ['masculino' => 'Masculino', 'femenino' => 'Femenino'], null, ['class' => 'form-control text-bold', 'placeholder' => '']) !!}
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group form-group-xs">
						{!! Form::label('edo_civil', 'Estado Civil') !!}
						{!! Form::select('edo_civil', ['soltero' => 'Soltero', 'casado' => 'Casado'], null, ['class' => 'form-control text-bold', 'placeholder' => '']) !!}
					</div>
				</div>
				
				<div class="clearfix"></div>

				<div class="col-md-4">
					<div class="form-group form-group-xs">
						{!! Form::label('pais_id', 'País de nacimiento') !!}
						{!! Form::select('pais_nacimiento_id', $paises, null, ['class' => 'form-control select2 text-bold', 'placeholder' => '']) !!}
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group form-group-xs">
						{!! Form::label('pais_id', 'Nacionalidad') !!}
						{!! Form::select('pais_nacionalidad_id', $paises, null, ['class' => 'form-control select2 text-bold', 'placeholder' => '']) !!}
					</div>
				</div>
				
			</div>
		</div>
		<div class="panel panel-flat border-top-lg border-top-primary">
			<div class="panel-heading">
				<h5 class="panel-title">Información de contacto</h5>
			</div>
			<div class="panel-body">
				<div class="col-md-4">
					<div class="form-group form-group-xs">
						{!! Form::label('telefono', '', ['class' => '']) !!}
						{!! Form::text('telefono', null, ['class' => 'form-control text-bold']) !!}
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group form-group-xs">
						{!! Form::label('celular', '', ['class' => '']) !!}
						{!! Form::text('celular', null, ['class' => 'form-control text-bold']) !!}
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group form-group-xs">
						{!! Form::label('email', '', ['class' => '']) !!}
						{!! Form::text('email', null, ['class' => 'form-control text-bold']) !!}
					</div>
				</div>

				<div class="col-md-12">
					<div class="form-group form-group-xs">
						{!! Form::label('direccion', 'Dirección', ['class' => '']) !!}
						{!! Form::textArea('direccion', null, ['class' => 'form-control text-bold', 'rows' => '2']) !!}
					</div>
				</div>


			</div>
		</div>

		<div class="panel">
			<div class="panel-body text-right">
				<button type="submit" class="btn border-slate text-slate-800 btn-flat legitRipple"><i class="icon-file-plus position-left"></i> Guardar información</button>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/paciente/edit.blade.php
@extends('layouts.app')

@section('page-title', $paciente->nombres.' '.$paciente->apellidos)

@section('content')
{!! Form::model($paciente->toArray()+$paciente->contacto->toArray(), ['route' => ['paciente.update', $paciente->id], 'method' => 'PUT', 'autocomplete' => 'off', 'id' => 'frmCreatePaciente']) !!}
<div class="row">
	<div class="col-md-8 col-lg-offset-2">
		<div class="panel panel-flat border-top-lg border-top-primary">
			<div class="panel-heading">
				<h5 class="panel-title">Datos personales</h5>
			</div>
			<div class="panel-body">

				<div class="col-md-4">

					<div class="form-group  form-group-xs">
						{!! Form::label('rut', 'RUT', ['class' => '']) !!}
						<div class="input-group">
							{!! Form::text('rut', null, ['class' => 'form-control text-bold rut']) !!}
							<span class="input-group-addon">-&nbsp;&nbsp; </span>
						</div>

					</div>
				</div>


				<div class="col-md-4">
					<div class="form-group form-group-xs">
						{!! Form::label('nombres', '', ['class' => '']) !!}
						{!! Form::text('nombres', null, ['class' => 'form-control input-roundless text-bold']) !!}
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group form-group-xs">
						{!! Form::label('apellidos', 'Apellidos', ['class' => '']) !!}
						{!! Form::text('apellidos', null, ['class' => 'form-control input-roundless text-bold']) !!}
					</div>
				</div>
				
				<div class="clearfix"></div>
				
				<div class="col-md-4">
					<div class="form-group form-group-xs">
						{!! Form::label('sexo', '', ['class' => '']) !!}
						{!! Form::select('sexo', ['masculino' => 'Masculino', 'femenino' => 'Femenino'], null, ['class' => 'form-control text-bold', 'placeholder' => '']) !!}
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group form-group-xs">
						{!! Form::label('edo_civil', 'Estado Civil') !!}
						{!! Form::select('edo_civil', ['soltero' => 'Soltero', 'casado' => 'Casado'], null, ['class' => 'form-control text-bold', 'placeholder' => '']) !!}
					</div>
				</div>
				
				<div class="clearfix"></div>

				<div class="col-md-4">
					<div class="form-group form-group-xs">
						{!! Form::label('pais_id', 'País de nacimiento') !!}
						{!! Form::select('pais_nacimiento_id', $paises, null, ['class' => 'form-control select2 text-bold', 'placeholder' => '']) !!}
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group form-group-xs">
						{!! Form::label('pais_id', 'Nacionalidad') !!}
						{!! Form::select('pais_nacionalidad_id', $paises, null, ['class' => 'form-control select2 text-bold', 'placeholder' => '']) !!}
					</div>
				</div>
				
			</div>
		</div>
		<div class="panel panel-flat border-top-lg border-top-primary">
			<div class="panel-heading">
				<h5 class="panel-title">Información de contacto</h5>
			</div>
			<div class="panel-body">
				<div class="col-md-4">
					<div class="form-group form-group-xs">
						{!! Form::label('telefono', '', ['class' => '']) !!}
						{!! Form::text('telefono', null, ['class' => 'form-control text-bold']) !!}
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group form-group-xs">
						{!! Form::label('celular', '', ['class' => '']) !!}
						{!! Form::text('celular', null, ['class' => 'form-control text-bold']) !!}
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group form-group-xs">
						{!! Form::label('email', '', ['class' => '']) !!}
						{!! Form::text('email', null, ['class' => 'form-control text-bold']) !!}
					</div>
				</div>

				<div class="col-md-12">
					<div class="form-group form-group-xs">
						{!! Form::label('direccion', 'Dirección', ['class' => '']) !!}
						{!! Form::textArea('direccion', null, ['class' => 'form-control text-bold', 'rows' => '2']) !!}
					</div>
				</div>


			</div>
		</div>

		<div class="panel">
			<div class="panel-body text-right">
				<button type="submit" class="btn border-slate text-slate-800 btn-flat legitRipple"><i class="icon-file-plus position-left"></i> Guardar información</button>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/paciente/index.blade.php
@extends('layouts.app')

@section('page-title', 'Maestro de Pacientes')

@push('css')
@endpush

@push('js-files')
{!! Html::script('assets/js/plugins/tables/datatables/datatables.min.js') !!}
@endpush

@push('js')
{!! Html::script('js/paciente-index.js') !!}
{!! Html::script('https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js') !!}
{!! Html::script('/vendor/datatables/buttons.server-side.js') !!}

@endpush

@section('opciones')
<ul class="nav navbar-nav">
	<li>
		<a href="{{ route('paciente.create') }}" >
			<i class="icon-user-plus position-left"></i> Agregar paciente
		</a>
	</li>

</ul>
@endsection

@section('content')

<div class="panel panel-flat">
	<div class="panel-body">
		{!! $dataTable->table() !!}
	</div>
</div>


<div class="modal fade" id="mdPacienteInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog modal-sm" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel"><i class="icon-vcard position-left"></i>Información del paciente</h4>
			</div>
			<div class="modal-body">
				<address>
					<strong>Nombres y Apellidos:</strong><span class="pull-right" id="paciente"></span><br>
					<strong>RUT:</strong> <span class="pull-right" id="rut"></span><br>
					<strong>Sexo:</strong> <span class="pull-right" id="sexo"></span><br>
					<strong>Nacionalidad:</strong> <span class="pull-right" id="nacionalidad"></span><br>
					<strong>Pais de nacimiento:</strong> <span class="pull-right" id="pais_nacimiento"></span>
				</address>

				<address>
					<strong>Correo electrónico: </strong><span class="pull-right" id="email"></span><br>
					<strong>Teléfono: </strong><span class="pull-right" id="telefono"></span><br>
					<strong>Celular: </strong><span class="pull-right" id="celular"></span><br>
				</address>
			</div>
			
		</div>
	</div>
</div>
<a href="{{ route('paciente.show', ':ID') }}" class="paciente_info hidden"></a>

{!! $dataTable->scripts() !!}
@endsection