routes/web.php
<?php

use App\Region;
use App\Comuna;


Route::group(['middleware' => ['web']], function () {
    
    Route::get('/login', function () {
        return view('auth/login');
    })->name('login');

	Route::post('/login', 'Auth\LoginController@login');
});


Route::group(['middleware' => ['auth', 'web']], function () {
	Route::post('logout', 'Auth\LoginController@logout')->name('logout');

	Route::get('/', function () {
	    return view('welcome');
	})->name('index');

	Route::get('find', 'SearchController@find');
	
	Route::get('paciente/search', 'PacienteController@autocomplete')->name('paciente.search');
	Route::resource('paciente', 'PacienteController');
	Route::resource('medico', 'MedicoController');
	Route::resource('usuario', 'UserController');
	Route::resource('roles', 'RolesController');
	Route::resource('agenda', 'AgendaController');
	Route::resource('sucursal', 'SucursalController');
	Route::resource('informe', 'InformeMedicoController');
	Route::resource('nefrologia', 'NefrologiaController');
	Route::resource('evolucion', 'EvolucionController');
	Route::resource('historial', 'HistorialController');
	Route::resource('horario', 'MedicoHorarioController');

	Route::get('historial/{id}/paciente/evolucion/mostrar', 'HistorialController@mostrarEvolucion')->name('mostrarEvolucion');

	Route::get('impresion/{id}/informe/medico', 'ImpresionesController@infMedico')->name('impresion.infMedico');
	Route::get('impresion/{id}/informe/nefrologia', 'ImpresionesController@infNefrologico')->name('impresion.infNefrologico');
	Route::get('impresion/{id}/informe/evolucion', 'ImpresionesController@infEvolucion')->name('impresion.infEvolucion');

	Route::post('configuracion/usuario/sucursal', 'UserConfiguracionController@cambioSucursal')->name('usuario.configuracion.sucursal');

	Route::get('paciente/{id}/comprobar', function($rut) {
	    $paciente = \App\Paciente::where('rut', str_replace('.', '', $rut))->where('rut_v', digitoVerificador($rut))->first();
	    if (count($paciente)>0) {
	    	return response()->json(['paciente' => $paciente, 'result' => true]);
	    }
	    return response()->json(['paciente' => [], 'result' => false]);
	})->name('paciente.comprobar');

	Route::get('global/regiones/{pais_id}', function ($pais_id) {
		return Region::where('pais_id', $pais_id)->orderBy('descripcion')->pluck('descripcion', 'id');
	})->name('global.regiones');

	Route::get('global/comunas/{region_id}', function ($region_id) {
		return Comuna::where('region_id', $region_id)->orderBy('descripcion')->pluck('descripcion', 'id');
	})->name('global.comunas');

	Route::get('digito/verificador/{rut}', function($rut){
		$digito = digitoVerificador($rut);
		return response()->json($digito);
	})->name('digito.verificador');

});

app/Comuna.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comuna extends Model
{
    protected $table = 'comunas';

    protected $guarded = [];
}

app/Especialidad.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Especialidad extends Model
{
    //
}

app/InfEvoMedica.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class InfEvoMedica extends Model
{
    protected $table = 'inf_evo_medica';

    protected $guarded = [];

    public function medico()
    {
    	return $this->belongsTo('App\Medico');
    }

    public function paciente()
    {
    	return $this->belongsTo('App\Paciente');
    }

    public function sucursal()
    {
        return $this->belongsTo('App\Sucursal');
    }
}

app/InfMedico.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class InfMedico extends Model
{
    protected $table = 'inf_medico';

    protected $guarded = [];

    public function medico()
    {
    	return $this->belongsTo('App\Medico');
    }

    public function paciente()
    {
    	return $this->belongsTo('App\Paciente');
    }

    public function sucursal()
    {
        return $this->belongsTo('App\Sucursal');
    }
}

app/InfNefrologia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class InfNefrologia extends Model
{
    protected $table = 'inf_nefrologia';

    protected $guarded = [];

    public function medico()
    {
    	return $this->belongsTo('App\Medico');
    }

    public function paciente()
    {
    	return $this->belongsTo('App\Paciente');
    }

    public function sucursal()
    {
        return $this->belongsTo('App\Sucursal');
    }
}

app/Medico.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Medico extends Model
{
    protected $table = 'medicos';

    protected $guarded = [];

    public function contacto()
    {
    	return $this->hasOne('App\MedicoContacto');
    }

    public function horario()
    {
    	return $this->hasMany('App\MedicoHorario');
    }

}

app/MedicoContacto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MedicoContacto extends Model
{
    protected $table = 'medico_contactos';

    protected $guarded = [];
}

app/MedicoHorario.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MedicoHorario extends Model
{
    protected $table = 'medico_horarios';

    protected $guarded = [];
}

app/Paciente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Paciente extends Model
{
    protected $table = 'pacientes';

    protected $guarded = [];


    public function contacto()
    {
        return $this->hasOne('App\PacienteContacto');
    }

    public function diagnostico()
    {
        return $this->hasOne('App\PacienteDiagnostico');
    }

    //HISTORIAL MEDICO DEL PACIENTE

    public function infMedico()
    {
        return $this->hasMany('App\InfMedico');
    }

    public function infNefrologico()
    {
        return $this->hasMany('App\InfNefrologia');
    }

    public function infEvoMedica()
    {
        return $this->hasMany('App\InfEvoMedica');
    }
}

app/PacienteContacto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PacienteContacto extends Model
{
    protected $table = 'paciente_contactos';

    protected $guarded = [];
}

app/PacienteDiagnostico.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PacienteDiagnostico extends Model
{
    protected $table = 'paciente_diagnosticos';

    protected $guarded = [];
}

app/Pais.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pais extends Model
{
    protected $table = 'paises';

    protected $guarded = [];
}

app/Patologia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Patologia extends Model
{
    //
}

app/Permission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Zizaco\Entrust\EntrustPermission;

class Permission extends EntrustPermission
{
    //
}

app/Region.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Region extends Model
{
    protected $table = 'regiones';

    protected $guarded = [];
}

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Zizaco\Entrust\EntrustRole;

class Role extends EntrustRole
{
    //
}

app/Sucursal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sucursal extends Model
{
    protected $table = 'sucursales';

    protected $guarded = [];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use Notifiable, EntrustUserTrait;

    protected $fillable = [
        'usuario', 'email', 'password', 'login', 'tipo'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    public function medico()
    {
        return $this->hasOne('App\Medico');
    }

    public function sucursales()
    {
        return $this->hasMany('App\UserSucursal');
    }

    public function configuracion()
    {
        return $this->hasOne('App\UserConfiguracion');
    }
}

app/UserConfiguracion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserConfiguracion extends Model
{
    protected $table = 'user_configuracion';

    protected $guarded = [];

    public function sucursal()
    {
    	return $this->belongsTo('App\Sucursal');
    }

}

app/UserSucursal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserSucursal extends Model
{
    protected $table = 'user_sucursales';

    protected $guarded = [];
    
    public $timestamps = false;
    public $incrementing = false;

    public function sucursal()
    {
    	return $this->belongsTo('App\Sucursal');
    }
}

resources/views/ficham/elementos/infCabecera.blade.php
<fieldset>
	<legend class="text-semibold">
		<i class="icon-file-text2 position-left"></i>
		Cabecera del informe
	</legend>

	<div class="row">
		<div class="col-md-3">
			<div class="form-group form-group-sm">
				{!! Form::label('rut_paciente', 'RUT Paciente', ['class' => '']) !!}
				<div class="input-group">
					{!! Form::text('rut_paciente', null, ['class' => 'form-control rut']) !!}
					<span class="input-group-addon">-&nbsp;&nbsp; </span>
				</div>
			</div>
		</div>
		<div class="col-md-3">
			<div class="form-group form-group-sm">
				{!! Form::label('paciente_info', '&nbsp;', ['class' => '']) !!}
				{!! Form::text('paciente_info', null, ['class' => 'form-control rut', 'disabled' => 'disabled']) !!}
			</div>
			<span class="paciente-nombre"></span>
		</div>

		<div class="col-md-3">
			<div class="form-group form-group-sm">
				{!! Form::label('sucursal_id', 'Sucursal', ['class' => '']) !!}
				{!! Form::text('sucursal_id', Auth::user()->configuracion->sucursal->nombre, ['class' => 'form-control rut', 'disabled' => 'disabled']) !!}
			</div>
		</div>

		<div class="col-md-3">
			<div class="form-group form-group-sm">
				{!! Form::label('fecha_informe', '', ['class' => '']) !!}
				{!! Form::text('fecha_informe', date('d/m/Y'), ['class' => 'form-control pickadate']) !!}
			</div>
		</div>
	</div>
</fieldset>

resources/views/ficham/elementos/modalPacienteCreate.blade.php
<a href="{{ route('paciente.comprobar', ':ID') }}" class="comprobar"></a>

<div class="modal fade" id="mdPaciente" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog modal-sm" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Paciente <small class="display-block">Agregar información básica</small></h4>
			</div>
			{!! Form::open(['route' => 'paciente.store', 'class' => 'form-horizontal']) !!}
			<div class="modal-body">

				<div class="form-group  form-group-xs">
					{!! Form::label('rut_register', 'RUT', ['class' => 'label-control col-md-4']) !!}
					<div class="col-md-8">
						<div class="input-group">
							{!! Form::text('rut_register', null, ['class' => 'form-control text-bold rut']) !!}
							<span class="input-group-addon">-&nbsp;&nbsp; </span>
						</div>
					</div>
				</div>


				<div class="form-group form-group-xs">
					{!! Form::label('nombres', '', ['class' => 'control-label col-md-4']) !!}
					<div class="col-md-8">
						{!! Form::text('nombres', null, ['class' => 'form-control input-roundless text-bold']) !!}
					</div>
				</div>

				<div class="form-group form-group-xs">
					{!! Form::label('apellidos', 'Apellidos', ['class' => 'control-label col-md-4']) !!}
					<div class="col-md-8">
						{!! Form::text('apellidos', null, ['class' => 'form-control input-roundless text-bold']) !!}
					</div>
				</div>
				
				
				<div class="form-group form-group-xs">
					{!! Form::label('sexo', '', ['class' => 'control-label col-md-4']) !!}
					<div class="col-md-8">
						{!! Form::select('sexo', ['masculino' => 'Masculino', 'femenino' => 'Femenino'], null, ['class' => 'form-control text-bold', 'placeholder' => '']) !!}
					</div>
				</div>

				<div class="form-group form-group-xs">
					{!! Form::label('edo_civil', 'Estado Civil', ['class' => 'control-label col-md-4']) !!}
					<div class="col-md-8">
						{!! Form::select('edo_civil', ['soltero' => 'Soltero', 'casado' => 'Casado'], null, ['class' => 'form-control text-bold', 'placeholder' => '']) !!}
					</div>
				</div>
				
				<div class="form-group form-group-xs">
					{!! Form::label('pais_id', 'País de nacimiento', ['class' => 'control-label col-md-4']) !!}
					<div class="col-md-8">
						{!! Form::select('pais_nacimiento_id', [], null, ['class' => 'form-control select2 text-bold', 'placeholder' => '']) !!}
					</div>
				</div>

				<div class="form-group form-group-xs">
					{!! Form::label('pais_id', 'Nacionalidad', ['class' => 'control-label col-md-4']) !!}
					<div class="col-md-8">
						{!! Form::select('pais_nacionalidad_id', [], null, ['class' => 'form-control select2 text-bold', 'placeholder' => '']) !!}
					</div>
				</div>
			</div>
			<div class="modal-footer">
				@submit_button(Guardar información)
			</div>
			{!! Form::close() !!}
		</div>
	</div>
</div>

resources/views/ficham/informe/edit.blade.php
@extends('layouts.app')

@push('js-files')
{!! Html::script('assets/js/plugins/forms/styling/uniform.min.js') !!}
{!! Html::script('assets/js/plugins/pickers/pickadate/picker.js') !!}
{!! Html::script('assets/js/plugins/pickers/pickadate/picker.date.js') !!}


{!! Html::script('assets/js/plugins/forms/inputs/formatter.min.js') !!}


{!! Html::script('assets/js/plugins/forms/inputs/typeahead/typeahead.bundle.min.js') !!}
@endpush

@push('js')
{!! Html::script('js/ficham-informe-register.js') !!}
{!! Html::script('vendor/jsvalidation/js/jsvalidation.js') !!}

{!! JsValidator::formRequest('App\Http\Requests\InformeMedicoRequest', '#frmInforme'); !!}
@endpush

@section('page-title', 'Informe médico')

@section('opciones')
<ul class="nav navbar-nav">
	<li class="active"><a href="#" data-toggle="modal" data-target="#mdPaciente"><i class="icon-users2 position-left"></i> Agregar paciente</a></li>
</ul>
@endsection

@section('content')
{!! Form::model($informe->toArray()+$informe->paciente->toArray(), ['route' => ['informe.update', $informe->id], 'method' => 'PUT', 'autocomplete' => 'off', 'id' => 'frmEvolucionMedica']) !!}

<div class="alert alert-warning alert-styled-right hide" id="alert">
	<button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
	<span class="text-semibold">Warning!</span> Better <a href="#" class="alert-link">check yourself</a>, you're not looking too good.
	<ul class="list-condensed error"></ul>
</div>
{!! Form::open(['route' => 'informe.store', 'id' => 'frmInforme']) !!}
<div class="panel panel-flat border-top-primary">

	<div class="panel-body">
		@include('ficham.elementos.infCabecera')

		<fieldset>

			<legend class="text-semibold">
				<table width='50%'>
					<tr>
						<h4><i class="icon-reading position-left"></i>
						Detalles del Informe Paciente: <strong>{{ $informe->paciente->nombres }} {{ $informe->paciente->apellidos }}</strong></h4>
					</tr>
					<tr>
						<h5>Folio: <strong>{{ $informe->id }}</strong> Fecha: <strong>{{ $informe->fecha_informe }}</strong></h5>
					</tr>
				</table>
			</legend>
				<div class="form-group">
					{!! Form::label('diagnostico', 'Diagnóstico', ['class' => '']) !!}
					{!! Form::textArea('diagnostico', null, ['class' => 'form-control', 'rows' => 5]) !!}
				</div>

				<div class="form-group">
					{!! Form::label('tratamiento', '', ['class' => '']) !!}
					{!! Form::textArea('tratamiento', null, ['class' => 'form-control', 'rows' => 5]) !!}
				</div>

				<div class="form-group">
					{!! Form::label('observaciones', '', ['class' => '']) !!}
					{!! Form::textArea('observaciones', null, ['class' => 'form-control', 'rows' => 5]) !!}
				</div>
		</fieldset>
		
	</div>
	<div class="panel-footer text-right pr-20">
		<button type="submit" class="btn btn-primary">Actualizar informe <i class="icon-arrow-right14 position-right"></i></button>
	</div>
</div>
{!! Form::close() !!}

@include('ficham.elementos.modalPacienteCreate')


@endsection

resources/views/ficham/informe/index.blade.php
@extends('layouts.app')

@push('js-files')
{!! Html::script('assets/js/plugins/forms/styling/uniform.min.js') !!}
{!! Html::script('assets/js/plugins/pickers/pickadate/picker.js') !!}
{!! Html::script('assets/js/plugins/pickers/pickadate/picker.date.js') !!}


{!! Html::script('assets/js/plugins/forms/inputs/formatter.min.js') !!}


{!! Html::script('assets/js/plugins/forms/inputs/typeahead/typeahead.bundle.min.js') !!}
@endpush

@push('js')
{!! Html::script('js/ficham-informe-register.js') !!}
{!! Html::script('vendor/jsvalidation/js/jsvalidation.js') !!}

{!! JsValidator::formRequest('App\Http\Requests\InformeMedicoRequest', '#frmInforme'); !!}
@endpush

@section('page-title', 'Informe médico')

@section('opciones')
<ul class="nav navbar-nav">
	<li class="active"><a href="#" data-toggle="modal" data-target="#mdPaciente"><i class="icon-users2 position-left"></i> Agregar paciente</a></li>
</ul>
@endsection

@section('content')
<div class="alert alert-warning alert-styled-right hide" id="alert">
	<button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
	<span class="text-semibold">Warning!</span> Better <a href="#" class="alert-link">check yourself</a>, you're not looking too good.
	<ul class="list-condensed error"></ul>
</div>
{!! Form::open(['route' => 'informe.store', 'id' => 'frmInforme']) !!}
<div class="panel panel-flat border-top-primary">

	<div class="panel-body">
		@include('ficham.elementos.infCabecera')

		<fieldset>
			<legend class="text-semibold">
				<i class="icon-reading position-left"></i>
				Detalles del Informe
			</legend>
				<div class="form-group">
					{!! Form::label('diagnostico', 'Diagnóstico', ['class' => '']) !!}
					{!! Form::textArea('diagnostico', null, ['class' => 'form-control', 'rows' => 5]) !!}
				</div>

				<div class="form-group">
					{!! Form::label('tratamiento', '', ['class' => '']) !!}
					{!! Form::textArea('tratamiento', null, ['class' => 'form-control', 'rows' => 5]) !!}
				</div>

				<div class="form-group">
					{!! Form::label('observaciones', '', ['class' => '']) !!}
					{!! Form::textArea('observaciones', null, ['class' => 'form-control', 'rows' => 5]) !!}
				</div>
		</fieldset>
		
	</div>
	<div class="panel-footer text-right pr-20">
		<button type="submit" class="btn btn-primary">Cargar informe <i class="icon-arrow-right14 position-right"></i></button>
	</div>
</div>
{!! Form::close() !!}


@include('ficham.elementos.modalPacienteCreate')


@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
{{--
App Name: GroupMedic
Version: 0.0.1
Author: Rosmar Blasquez
Website: 
Contact: reblasquez@gmail.com
Follow: 
Dribbble: 
Like: 
Purchase: 
Renew Support: 
License: 
--}}
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>GroupMedic</title>

    {{-- Global stylesheets --}}
    {!! Html::style('https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900') !!}
    {!! Html::style('assets/css/icons/icomoon/styles.css') !!}
    {!! Html::style('assets/css/bootstrap.css') !!}
    {!! Html::style('assets/css/core.css') !!}
    {!! Html::style('assets/css/components.css') !!}
    {!! Html::style('assets/css/colors.css') !!}
    {!! Html::style('assets/css/extras/animate.min.css') !!}
    {!! Html::style('css/app.css') !!}
    {!! Html::style('css/sweetalert.css') !!}

    @stack('css')
    {{-- /global stylesheets --}}

    {{-- Core JS files --}}
    {!! Html::script('js/sweetalert.min.js') !!}
    {!! Html::script('assets/js/plugins/loaders/pace.min.js') !!}
    {!! Html::script('assets/js/core/libraries/jquery.min.js') !!}
    {!! Html::script('assets/js/core/libraries/bootstrap.min.js') !!}
    {!! Html::script('assets/js/plugins/ui/nicescroll.min.js') !!}
    {!! Html::script('assets/js/plugins/loaders/blockui.min.js') !!}
    {{-- /core JS files --}}

    {{-- Theme JS files --}}
    {!! Html::script('assets/js/plugins/forms/selects/bootstrap_select.min.js') !!}
    @stack('js-files')
    
    {!! Html::script('assets/js/core/app.js') !!}
    {!! Html::script('js/app.js') !!}
    {!! Html::script('assets/js/pages/layout_fixed_custom.js') !!}
    
    @stack('js')
    {{--  {!! Html::script('assets/js/plugins/ui/ripple.min.js') !!} --}}

    {{-- /theme JS files --}}
</head>

<body class="navbar-top">

    {{-- Navbar --}}
    @include('layouts.elementos.navbar')
    {{-- /Navbar --}}

    {{-- Page container --}}
    <div class="page-container">

        {{-- Page content --}}
        <div class="page-content">

            {{-- Main sidebar --}}
            @include('layouts.elementos.sidebar')
            {{-- /Main sidebar --}}

            {{-- Main content --}}
            <div class="content-wrapper">

                {{-- Page header --}}
                @include('layouts.elementos.page-header')
                {{-- /Page header --}}

                {{-- Content area --}}
                <div class="content">

                    @yield('content')
                    
                    {{-- sidebar-oposite --}}
                    @permission(['usuarios_create', 'usuarios_edit', 'usuarios_delete', 'usuarios_show'])
                    @include('layouts.elementos.sidebar-opposite')
                    @endrole
                    {{-- /sidebar-oposite --}}

                    {{-- footer --}}
                    @include('layouts.elementos.footer')
                    {{-- /footer --}}

                </div>
                {{-- /Content area --}}

            </div>
            {{-- /Main content --}}

        </div>
        {{-- /Page content --}}

    </div>
    {{-- /Page container --}}
    

    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
        {{ csrf_field() }}
    </form>
    <a href="{{ route('digito.verificador', ':RUT') }}" class="hide digito-verificador"></a>
    @include('sweet::alert')
    
</body>
</html>

resources/views/layouts/elementos/sidebar-opposite.blade.php
<div class="sidebar sidebar-opposite sidebar-inverse sidebar-fixed">

    <div class="sidebar-content">

        <div class="sidebar-category">
            <div class="category-title">
                <span><i class="icon-users position-left"></i>Usuarios</span>
                <ul class="icons-list">
                    <li><a href="#" data-action="collapse"></a></li>
                </ul>
            </div>

            <div class="category-content">
                <div class="row">
                    <div class="col-xs-6">
                        <a href="{{ route('usuario.index') }}" class="btn bg-teal-400 btn-block btn-float btn-float-lg">
                            <i class="icon-cogs"></i> <span>Administrar</span>
                        </a>
                    </div>
                    <div class="col-xs-6">
                        <a href="{{ route('roles.index') }}" class="btn bg-purple-300 btn-block btn-float btn-float-lg">
                            <i class="icon-equalizer2"></i> <span>Roles</span>
                        </a>
                    </div>


                </div>
            </div>
        </div>

        <div class="sidebar-category category-collapsed">
            <div class="category-title">
                <span><i class="icon-office position-left"></i>Sucursales</span>
                <ul class="icons-list">
                    <li><a href="#" data-action="collapse"></a></li>
                </ul>
            </div>

            <div class="category-content no-padding">
                <ul class="navigation navigation-alt navigation-accordion">
                    <li><a href="{{ route('sucursal.index') }}"><i class="icon-menu6"></i> <span>Administrar</span></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/elementos/sidebar.blade.php
<div class="sidebar sidebar-main sidebar-default sidebar-fixed">
    <div class="sidebar-content">
        <div class="sidebar-user">
            <div class="category-content">
                <div class="media">
                    <a href="#" class="media-left"><img src="{{ asset('assets/images/image.png') }}" class="img-circle img-sm" alt=""></a>
                    <div class="media-body">
                        <span class="media-heading text-semibold">{{ Auth::user()->usuario }}</span>
                        <div class="text-size-mini">
                            {{ collect(Auth::user()->roles)->first()->display_name }}
                        </div>
                    </div>

                    <div class="media-right media-middle">
                        <ul class="icons-list">
                            <li>
                                <a href="#user-nav" data-toggle="collapse"><i class="icon-cog3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="navigation-wrapper collapse" id="user-nav">
                <ul class="navigation">
                    <li><a href="#" class="legitRipple"><i class="icon-cog5"></i> <span>Datos personales</span></a></li>
                    <li><a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="icon-switch2"></i> <span>Cerrar sesión</span></a></li>
                </ul>
            </div>
        </div>


        <div class="sidebar-category sidebar-category-visible">
            <div class="category-content no-padding">
                <ul class="navigation navigation-main navigation-accordion navigation-icons-right navigation-xs">

                    <li><a href="{{ route('index') }}"><i class="icon-home4"></i> <span>Panel Administrativo</span></a></li>
                    
                    <li class="navigation-header"><span>Ficha Médica</span> <i class="icon-menu" title="Maestros"></i></li>
                    
                    <li><a href="{{ route('informe.index') }}"><i class="icon-profile"></i> <span>Informe médico</span></a></li>
                    <li><a href="{{ route('nefrologia.index') }}"><i class="icon-profile"></i> <span>Informe nefrología</span></a></li>
                    <li><a href="{{ route('evolucion.index') }}"><i class="icon-profile"></i> <span>Evolución médica</span></a></li>

                    <li class="navigation-header"><span>Maestros</span> <i class="icon-menu" title="Maestros"></i></li>

                    @permission(['agenda_create', 'agenda_edit', 'agenda_delete', 'agenda_show'])
                    <li><a href="{{ route('agenda.index') }}"><i class="icon-list-unordered"></i> <span>Agenda Médica</span></a></li>
                    @endpermission
                    
                    @permission(['paciente_create', 'paciente_edit', 'paciente_delete', 'paciente_show'])
                    <li><a href="{{ route('paciente.index') }}"><i class="icon-users"></i> <span>Pacientes</span></a></li>
                    @endpermission
                    
                    @permission(['medico_create', 'medico_edit', 'medico_delete', 'medico_show'])
                    @if (Auth::user()->hasRole(['med']))
                    <li><a href="{{ route('medico.edit', Auth::user()->medico->id) }}"><i class="icon-user-tie"></i> <span>Información de médico</span></a></li>
                    @else
                    <li><a href="{{ route('medico.index') }}"><i class="icon-user-tie"></i> <span>Médicos</span></a></li>
                    @endif
                    @endpermission
                </ul>
            </div>
        </div>

    </div>
</div>